# Generated by Django 4.1.4 on 2022-12-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=14, null=True)),
            ],
        ),
    ]
