# Generated by Django 4.1.4 on 2022-12-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entreprise',
            field=models.BooleanField(default=False),
        ),
    ]
